asf-rest-config: 
  # Either "username_password" or "omni_auth" 
  auth_scheme: username_password 
  #username_password 
  adapter: activesalesforce 
  url: https://login.salesforce.com 
  username: developer@michaelpatrickstewart.com
  password: stillnotused3  
  api_version: 21.0 
  #omni_auth 
  #consumer_key: notused
  #consumer_secret: notused
